import type { Team, Match, Scorer } from "./types"

export const TOURNAMENT = {
  name: "IMRT 3x3 Basketball Championship 2026",
  dates: "March 15 - 17, 2026",
  venue: "IMRT Indoor Arena, Main Court",
  tipOff: "2026-03-15T09:00:00",
}

export const mockTeams: Team[] = [
  {
    id: "t1",
    code: "IMRT-01",
    name: "Skyline Ballers",
    color: "#6B1728",
    category: "Men's Open",
    pool: "A",
    captain: { name: "Rahul Verma", email: "rahul@imrt.edu", phone: "+91 98765 43210", studentId: "IMRT-2024-01" },
    roster: [
      { name: "Rahul Verma", jersey: 7, height: "6'2\"", role: "Guard" },
      { name: "Aditya Singh", jersey: 11, height: "6'5\"", role: "Forward" },
      { name: "Karan Mehta", jersey: 23, height: "6'7\"", role: "Center" },
      { name: "Sameer Roy", jersey: 4, height: "6'0\"", role: "Wing", isSub: true },
    ],
    wins: 2,
    losses: 0,
    pointsFor: 42,
    pointsAgainst: 28,
    approved: true,
  },
  {
    id: "t2",
    code: "IMRT-02",
    name: "Court Kings",
    color: "#D4AF37",
    category: "Men's Open",
    pool: "A",
    captain: { name: "Vikram Nair", email: "vikram@imrt.edu", phone: "+91 98765 43211", studentId: "IMRT-2024-02" },
    roster: [
      { name: "Vikram Nair", jersey: 5, height: "6'1\"", role: "Guard" },
      { name: "Dev Patel", jersey: 14, height: "6'4\"", role: "Forward" },
      { name: "Arjun Das", jersey: 32, height: "6'6\"", role: "Center" },
      { name: "Neel Kapoor", jersey: 9, height: "5'11\"", role: "Wing", isSub: true },
    ],
    wins: 1,
    losses: 1,
    pointsFor: 35,
    pointsAgainst: 33,
    approved: true,
  },
  {
    id: "t3",
    code: "IMRT-03",
    name: "Hoopsters Elite",
    color: "#1E293B",
    category: "Men's Open",
    pool: "B",
    captain: { name: "Zain Khan", email: "zain@imrt.edu", phone: "+91 98765 43212", studentId: "IMRT-2024-03" },
    roster: [
      { name: "Zain Khan", jersey: 10, height: "6'3\"", role: "Guard" },
      { name: "Tanmay Joshi", jersey: 21, height: "6'5\"", role: "Forward" },
      { name: "Kabir Bedi", jersey: 33, height: "6'8\"", role: "Center" },
    ],
    wins: 2,
    losses: 0,
    pointsFor: 44,
    pointsAgainst: 30,
    approved: true,
  },
  {
    id: "t4",
    code: "IMRT-04",
    name: "Net Rippers",
    color: "#831843",
    category: "Men's Open",
    pool: "B",
    captain: { name: "Aman Gupta", email: "aman@imrt.edu", phone: "+91 98765 43213", studentId: "IMRT-2024-04" },
    roster: [
      { name: "Aman Gupta", jersey: 1, height: "6'0\"", role: "Guard" },
      { name: "Rohan Sen", jersey: 8, height: "6'3\"", role: "Forward" },
      { name: "Siddharth Rao", jersey: 15, height: "6'6\"", role: "Center" },
    ],
    wins: 0,
    losses: 2,
    pointsFor: 25,
    pointsAgainst: 41,
    approved: true,
  },
  {
    id: "t5",
    code: "IMRT-05",
    name: "Ballerinas 3x3",
    color: "#9F1239",
    category: "Women's Open",
    pool: "C",
    captain: { name: "Ananya Sharma", email: "ananya@imrt.edu", phone: "+91 98765 43214", studentId: "IMRT-2024-05" },
    roster: [
      { name: "Ananya Sharma", jersey: 3, height: "5'8\"", role: "Guard" },
      { name: "Priya Iyer", jersey: 12, height: "5'10\"", role: "Forward" },
      { name: "Neha Reddy", jersey: 22, height: "6'1\"", role: "Center" },
    ],
    wins: 2,
    losses: 0,
    pointsFor: 38,
    pointsAgainst: 20,
    approved: true,
  },
  {
    id: "t6",
    code: "IMRT-06",
    name: "Crossover Queens",
    color: "#4C1D95",
    category: "Women's Open",
    pool: "C",
    captain: { name: "Diya Sen", email: "diya@imrt.edu", phone: "+91 98765 43215", studentId: "IMRT-2024-06" },
    roster: [
      { name: "Diya Sen", jersey: 6, height: "5'7\"", role: "Guard" },
      { name: "Rhea Pillai", jersey: 13, height: "5'9\"", role: "Forward" },
      { name: "Meera Menon", jersey: 24, height: "6'0\"", role: "Center" },
    ],
    wins: 1,
    losses: 1,
    pointsFor: 30,
    pointsAgainst: 29,
    approved: true,
  },
  {
    id: "t7",
    code: "IMRT-07",
    name: "CSE Titans",
    color: "#0369A1",
    category: "Inter-Department",
    pool: "D",
    captain: { name: "Karthik Raja", email: "karthik@imrt.edu", phone: "+91 98765 43216", studentId: "IMRT-2024-07" },
    roster: [
      { name: "Karthik Raja", jersey: 2, height: "6'1\"", role: "Guard" },
      { name: "Varun Kumar", jersey: 7, height: "6'4\"", role: "Forward" },
      { name: "Akash Deep", jersey: 25, height: "6'6\"", role: "Center" },
    ],
    wins: 2,
    losses: 0,
    pointsFor: 40,
    pointsAgainst: 22,
    approved: true,
  },
  {
    id: "t8",
    code: "IMRT-08",
    name: "ECE Dunkers",
    color: "#047857",
    category: "Inter-Department",
    pool: "D",
    captain: { name: "Sanjay Patel", email: "sanjay@imrt.edu", phone: "+91 98765 43217", studentId: "IMRT-2024-08" },
    roster: [
      { name: "Sanjay Patel", jersey: 4, height: "6'0\"", role: "Guard" },
      { name: "Manoj Tiwari", jersey: 11, height: "6'3\"", role: "Forward" },
      { name: "Nikhil Verma", jersey: 30, height: "6'5\"", role: "Center" },
    ],
    wins: 1,
    losses: 1,
    pointsFor: 31,
    pointsAgainst: 33,
    approved: true,
  },
]

export const mockMatches: Match[] = [
  {
    id: "m1",
    court: "Court 1 (Main Arena)",
    category: "Men's Open",
    teamAId: "t1",
    teamBId: "t2",
    scoreA: 14,
    scoreB: 11,
    status: "live",
    time: "10:00 AM",
    round: "Pool Stage",
    venue: "IMRT Indoor Arena",
  },
  {
    id: "m2",
    court: "Court 2",
    category: "Men's Open",
    teamAId: "t3",
    teamBId: "t4",
    scoreA: 21,
    scoreB: 15,
    status: "completed",
    time: "10:30 AM",
    round: "Pool Stage",
    venue: "IMRT Indoor Arena",
  },
  {
    id: "m3",
    court: "Court 1 (Main Arena)",
    category: "Women's Open",
    teamAId: "t5",
    teamBId: "t6",
    scoreA: 19,
    scoreB: 12,
    status: "completed",
    time: "11:00 AM",
    round: "Pool Stage",
    venue: "IMRT Indoor Arena",
  },
  {
    id: "m4",
    court: "Court 2",
    category: "Inter-Department",
    teamAId: "t7",
    teamBId: "t8",
    scoreA: 0,
    scoreB: 0,
    status: "upcoming",
    time: "11:30 AM",
    round: "Pool Stage",
    venue: "IMRT Indoor Arena",
  },
  {
    id: "m5",
    court: "Court 1 (Main Arena)",
    category: "Men's Open",
    teamAId: "t1",
    teamBId: "t3",
    scoreA: 0,
    scoreB: 0,
    status: "upcoming",
    time: "02:00 PM",
    round: "Quarter Finals",
    venue: "IMRT Indoor Arena",
  },
]

export const mockScorers: Scorer[] = [
  { id: "s1", playerName: "Rahul Verma", teamId: "t1", points: 26, games: 2 },
  { id: "s2", playerName: "Zain Khan", teamId: "t3", points: 24, games: 2 },
  { id: "s3", playerName: "Ananya Sharma", teamId: "t5", points: 22, games: 2 },
  { id: "s4", playerName: "Karthik Raja", teamId: "t7", points: 21, games: 2 },
  { id: "s5", playerName: "Vikram Nair", teamId: "t2", points: 20, games: 2 },
]
